Added 6/10 tasks for 27-28
Pozharitskiy/hiqo-js pull request #2
Opened 2019-06-27 16:50 UTC by Pozharitskiy

2019-06-28 15:02 UTC, angelinabylitskaya requested changes

2019-06-28 15:02 UTC, angelinabylitskaya commented on 27.06/eigth.js
> +function find(array, foo) {
Methods should return value.

2019-06-28 15:02 UTC, angelinabylitskaya commented on 27.06/fifth.js
> +function fromPairs(array) {
Try to use "reduce" method here

2019-06-28 15:02 UTC, angelinabylitskaya commented on 27.06/nineth.js
> +    const map = new Map();
Try to use "reduce" method here

2019-06-28 15:02 UTC, angelinabylitskaya commented on 27.06/tenth.js
> +   /*Of course :)*/ (JSON.stringify(ob1) === JSON.stringify(ob2)) ? console.log(true) : console.log(false);
No need to use ?: here.

2019-06-28 15:02 UTC, angelinabylitskaya commented on 27.06/third.js
> +    const find = (element, index, array) => {
Try to use existing js methods

2019-07-01 08:18 UTC, Pozharitskiy commented on 27.06/tenth.js
> +   /*Of course :)*/ (JSON.stringify(ob1) === JSON.stringify(ob2)) ? console.log(true) : console.log(false);
Fixed. Thanks

2019-07-01 08:39 UTC, Pozharitskiy commented on 27.06/eigth.js
> +function find(array, foo) {
Done

2019-07-01 08:39 UTC, Pozharitskiy commented on 27.06/fifth.js
> +function fromPairs(array) {
Done

2019-07-01 08:58 UTC, Pozharitskiy commented on 27.06/nineth.js
> +    const map = new Map();
Done

2019-07-01 09:27 UTC, Pozharitskiy commented on 27.06/third.js
> +    const find = (element, index, array) => {
Done

2019-07-01 10:44 UTC, kobweb requested changes

2019-07-01 10:44 UTC, kobweb commented on 27.06/fifth.js
> +        let prop = item[0];
You should use `const` instead of `let` if your variable wouldn't change.

2019-07-01 10:44 UTC, kobweb commented on 27.06/fifth.js
> +        let prop = item[0];
It related to the whole code.

2019-07-01 10:44 UTC, kobweb commented on 27.06/fourth.js
> +    const lifehack = array.toString().split(",").map(Number);
It wouldn't work if you pass to the function something like that [1, ['qwe', [3, ['asd']], 5]]

2019-07-01 10:44 UTC, kobweb commented on 27.06/nineth.js
> +        (elem[foo(currentValue)] = elem[foo(currentValue)] || []).push(currentValue);
It's unreadable and unsupportable code. Refactor and simplify it.

2019-07-01 10:44 UTC, kobweb commented on 27.06/tenth.js
> +   /*Of course :)*/return JSON.stringify(ob1) === JSON.stringify(ob2);
Won't work if the objects will be the same but with the different fields order.

2019-07-01 13:12 UTC, Pozharitskiy commented on 27.06/fifth.js
> +        let prop = item[0];
Got it

2019-07-01 13:35 UTC, Pozharitskiy commented on 27.06/nineth.js
> +        (elem[foo(currentValue)] = elem[foo(currentValue)] || []).push(currentValue);
Done.

2019-07-01 21:50 UTC, ElizavetaSelivanova commented on 27.06/first.js
> +    console.log(container);
add `return`

2019-07-01 21:50 UTC, ElizavetaSelivanova commented on 27.06/fourth.js
> +// 	// TODO: implement function
- add `return`;
- read about `flat` method.

2019-07-01 21:50 UTC, ElizavetaSelivanova commented on 27.06/second.js
> +    const test = array1.filter(element => array2.includes(element));
incorrect name of variable

2019-07-01 21:50 UTC, ElizavetaSelivanova commented on 27.06/second.js
> +}
- add `return`;
- could be optimized.

2019-07-01 21:50 UTC, ElizavetaSelivanova commented on 27.06/seventh.js
> +}
- add `return`

2019-07-01 21:50 UTC, ElizavetaSelivanova commented on 27.06/sixth.js
> +}
- add `return`;
- could be optimized - no need to use nested `for`

2019-07-01 21:50 UTC, ElizavetaSelivanova commented on 27.06/tenth.js
> +}
- the solution should be simplified and more readable;
- read about `let`, `const` and difference from `var`;
- review naming of variables.

2019-07-02 07:18 UTC, Pozharitskiy commented on 27.06/tenth.js
> +   /*Of course :)*/return JSON.stringify(ob1) === JSON.stringify(ob2);
Solved

2019-07-02 07:21 UTC, Pozharitskiy commented on 27.06/second.js
> +    const test = array1.filter(element => array2.includes(element));
Fixed

2019-07-02 07:36 UTC, Pozharitskiy commented on 27.06/second.js
> +}
oh, it can  be more and more simple. Fixed

2019-07-02 07:36 UTC, Pozharitskiy commented on 27.06/first.js
> +    console.log(container);
Done

2019-07-02 08:11 UTC, Pozharitskiy commented on 27.06/fourth.js
> +    const lifehack = array.toString().split(",").map(Number);
Fixed

2019-07-02 08:12 UTC, Pozharitskiy commented on 27.06/fourth.js
> +// 	// TODO: implement function
Thanks! It was helpful. Done

2019-07-02 08:14 UTC, Pozharitskiy commented on 27.06/seventh.js
> +}
Done

2019-07-02 08:26 UTC, Pozharitskiy commented on 27.06/sixth.js
> +}
I found more elegant solution. Check it out please

2019-07-02 08:43 UTC, Pozharitskiy commented on 27.06/tenth.js
> +}
1) I added comments to the solution. Hope it will be more readable.
2) I know about that, but ... (my bad) Fixed
3) Done

2019-07-04 13:57 UTC, merged