02.07
Pozharitskiy/hiqo-js pull request #3
Opened 2019-07-04 13:57 UTC by Pozharitskiy

2019-07-04 15:37 UTC, dlos-hiqo requested changes

2019-07-04 15:37 UTC, dlos-hiqo commented on 02.07/4.js
> +curry = function (fn) {
Please rewrite using .bind

2019-07-04 15:37 UTC, dlos-hiqo commented on 02.07/5.js
> +let timerId;
Please rewrite using closure

2019-07-04 15:37 UTC, dlos-hiqo commented on 02.07/6.js
> +            cache[n] = result;
It will not work as expected. Please use hash for parameters

2019-07-08 10:32 UTC, Pozharitskiy commented on 02.07/4.js
> +curry = function (fn) {
Done

2019-07-08 10:32 UTC, Pozharitskiy commented on 02.07/5.js
> +let timerId;
Done

2019-07-08 10:32 UTC, Pozharitskiy commented on 02.07/6.js
> +            cache[n] = result;
Done

2019-07-09 11:45 UTC, merged